# This is a basic workflow to help you get started with Actions

name:  GitHub Actions Demo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
  # Every sunday at 6:15 UTC
  - cron:  '15 06 * * SUN'
  # on every push to the main branch, but not when there are changes to files in the .github folder.
  push:
    paths:
    - './github/**'
    branches: [ "main" ]
  # Every sunday at 6:15 UTC  
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # print output
      - name: echo output
        run: |
          echo ${{ github.event_name }}
          echo ${{ github.base_ref }}

      # List all files in the repository
      - name: ls files
        run: tree ./
