name: Reuse other workflow

on:
  workflow_dispatch:
jobs:
  call-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: call-workflow 
        uses: ./.github/workflows/reusable.yml
        with:
          who-to-greet: '@octocat'
            
  use-output:
    runs-on: ubuntu-latest
    needs: [call-workflow]
    steps:
      - run: echo "Time was ${{ needs.call-workflow.outputs.current-time }}"
