name: Reuse other workflow

on:
  workflow_dispatch:
jobs:
  call-workflow:
    runs-on: ubuntu-latest
    outputs:
      id: current-time
      type: string    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: call-workflow 
        uses: ./.github/workflows/reusable.yml
        with:
          who-to-greet: '@octocat'
            
  use-output:
    runs-on: ubuntu-latest
    needs: [call-workflow]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0    
      - run: echo "Time was ${{ needs.call-workflow.outputs.current-time }}"
