name: Reuse other workflow

on:
  workflow_dispatch:


jobs:

  run:
    steps:
      uses: ./.github/workflows/reusable.yml
          with:
            who-to-greet: '@octocat'
            
      use-output:
          - run: echo "Time was ${{ steps.call-workflow.outputs.current-time }}"
