name: Reuse other workflow

on:
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: call-workflow 
        uses: ./.github/workflows/reusable.yml
        with:
          who-to-greet: '@octocat'
            
      - name: use-output
        run: |
          echo "Time was ${{ steps.call-workflow.outputs.current-time }}"
